[
    { "front": "What is the chemical symbol for gold?", "back": "Au" },
    { "front": "What planet is known as the Red Planet?", "back": "Mars" },
    { "front": "What is the most abundant gas in Earth's atmosphere?", "back": "Nitrogen" },
    { "front": "What is the powerhouse of the cell?", "back": "Mitochondria" },
    { "front": "What type of energy is stored in a stretched rubber band?", "back": "Potential energy" },
    { "front": "Which organ in the human body produces insulin?", "back": "Pancreas" },
    { "front": "What is the hardest natural substance on Earth?", "back": "Diamond" },
    { "front": "What is the process by which plants make their own food?", "back": "Photosynthesis" },
    { "front": "Which planet has the most moons?", "back": "Saturn" },
    { "front": "What is the speed of light in a vacuum?", "back": "Approximately 299,792,458 meters per second" },
    { "front": "What is the smallest unit of matter?", "back": "Atom" },
    { "front": "What is the chemical formula for water?", "back": "H₂O" },
    { "front": "Which element is necessary for respiration?", "back": "Oxygen" },
    { "front": "What is the most common element in the universe?", "back": "Hydrogen" },
    { "front": "What is the longest bone in the human body?", "back": "Femur" },
    { "front": "Which gas do plants absorb from the atmosphere?", "back": "Carbon dioxide (CO₂)" },
    { "front": "What type of rock is formed from cooled lava?", "back": "Igneous rock" },
    { "front": "Which scientist developed the theory of general relativity?", "back": "Albert Einstein" },
    { "front": "What is the main function of red blood cells?", "back": "Transport oxygen" },
    { "front": "What force keeps planets in orbit around the Sun?", "back": "Gravity" },
    { "front": "Which part of the brain controls balance and coordination?", "back": "Cerebellum" },
    { "front": "What is the unit of electric current?", "back": "Ampere" },
    { "front": "Which element has the atomic number 1?", "back": "Hydrogen" },
    { "front": "What do you call an organism that can make its own food?", "back": "Autotroph" },
    { "front": "Which part of the human eye controls the amount of light that enters?", "back": "Iris" },
    { "front": "What is the boiling point of water at sea level?", "back": "100°C (212°F)" },
    { "front": "What is the study of heredity called?", "back": "Genetics" },
    { "front": "What type of wave is a sound wave?", "back": "Longitudinal wave" },
    { "front": "Which vitamin is produced when the skin is exposed to sunlight?", "back": "Vitamin D" },
    { "front": "What is the atomic symbol for iron?", "back": "Fe" },
    { "front": "Which layer of the Earth is liquid?", "back": "Outer core" },
    { "front": "What is the name of the process by which a liquid turns into a gas?", "back": "Evaporation" },
    { "front": "Which planet has the shortest year?", "back": "Mercury" },
    { "front": "What is the only metal that is liquid at room temperature?", "back": "Mercury" },
    { "front": "Which part of the plant is responsible for photosynthesis?", "back": "Leaves" },
    { "front": "What is the largest organ in the human body?", "back": "Skin" },
    { "front": "What type of charge does a proton have?", "back": "Positive" },
    { "front": "What is the SI unit of force?", "back": "Newton" },
    { "front": "Which gas is responsible for the greenhouse effect?", "back": "Carbon dioxide (CO₂)" },
    { "front": "What is the process of breaking down food to release energy called?", "back": "Respiration" },
    { "front": "Which planet has a Great Red Spot?", "back": "Jupiter" },
    { "front": "What is the study of fossils called?", "back": "Paleontology" },
    { "front": "Which part of the atom contains protons and neutrons?", "back": "Nucleus" },
    { "front": "What is the largest planet in our solar system?", "back": "Jupiter" },
    { "front": "Which scientist developed the three laws of motion?", "back": "Isaac Newton" },
    { "front": "What do we call an animal that eats both plants and animals?", "back": "Omnivore" },
    { "front": "Which blood type is the universal donor?", "back": "O negative" },
    { "front": "What is the most common noble gas in Earth's atmosphere?", "back": "Argon" },
    { "front": "What type of simple machine is a ramp?", "back": "Inclined plane" }
]
