[
    { "front": "<img src='images/thinking/tm1.jpg'>", "back": "AHEAD: [predict, aim]<br>I think the next thing will be...<br>The consequence of this is likely to be..." },
    { "front": "<img src='images/thinking/tm2.jpg'>", "back": "BACK: [remember, reflect]<br>It was mentioned earlier that...<br>Let’s review..." },
    { "front": "<img src='images/thinking/tm3.jpg'>", "back": "CONNECT: [link, liken]<br>Connecting to what Toni said...<br>A useful analogy would be..." },
    { "front": "<img src='images/thinking/tm4.jpg'>", "back": "DIVIDE: [separate, list]<br>I would like to make a distinction between...<br>Breaking this down, there are three elements:..." },
    { "front": "<img src='images/thinking/tm5.jpg'>", "back": "EXPLAIN: [say how, clarify]<br>The causes of this are...<br>I think that what Ali means is..." },
    { "front": "<img src='images/thinking/tm6.jpg'>", "back": "FORMULATE: [suggest, propose]<br>My theory is that...<br>Let’s start with a rough draft..." },
    { "front": "<img src='images/thinking/tm7.jpg'>", "back": "GROUP: [sort, class]<br>Another way to organise these would be...<br>What these have in common is..." },
    { "front": "<img src='images/thinking/tm8.jpg'>", "back": "HEADLINE: [summarise, distil]<br>The most important point is...<br>What we are really talking about is..." },
    { "front": "<img src='images/thinking/tm9.jpg'>", "back": "INFER: [deduce, take from]<br>I can tell from this that...<br>From looking at the clues we can figure out..." },
    { "front": "<img src='images/thinking/tm10.jpg'>", "back": "JUSTIFY: [give reason, argue]<br>I think I am probably right because...<br>There are many arguments which verify this, for example..." },
    { "front": "<img src='images/thinking/tm11.jpg'>", "back": "KEYWORD: [highlight, pinpoint]<br>The central concept is...<br>The crux of the matter is..." },
    { "front": "<img src='images/thinking/tm12.jpg'>", "back": "LOOK/LISTEN: [notice, gather]<br>I have observed that...<br>I can see/hear/taste/smell/touch/feel..." },
    { "front": "<img src='images/thinking/tm13.jpg'>", "back": "MAINTAIN: [believe, affirm]<br>I maintain my position that...<br>Regardless of the popular view, I maintain that..." },
    { "front": "<img src='images/thinking/tm14.jpg'>", "back": "NEGATE: [disagree, oppose]<br>I would like to challenge something that Clarence said...<br>I would like to refute/dispute/rebut..." },
    { "front": "<img src='images/thinking/tm15.jpg'>", "back": "ORDER: [sequence, arrange]<br>First we should _____, then...<br>Let’s be systematic about this..." },
    { "front": "<img src='images/thinking/tm16.jpg'>", "back": "PICTURE: [imagine, put yourself]<br>Let's imagine that...<br>Looking at this from a different perspective,..." },
    { "front": "<img src='images/thinking/tm17.jpg'>", "back": "QUESTION: [ask, wonder]<br>I wonder...<br>What if...<br>It is possible that...?" },
    { "front": "<img src='images/thinking/tm18.jpg'>", "back": "RESPOND: [answer, reply]<br>I would like to respond to Jack's point...<br>I’m personally having quite an emotional reaction to this..." },
    { "front": "<img src='images/thinking/tm19.jpg'>", "back": "SIZE: [estimate, quantify]<br>Perhaps we should try to be more accurate...<br>The figures say..." },
    { "front": "<img src='images/thinking/tm20.jpg'>", "back": "TEST: [doubt, check]<br>Can we be certain that...<br>This seems questionable/dubious/suspicious..." },
    { "front": "<img src='images/thinking/tm21.jpg'>", "back": "USE: [try out, apply]<br>Shall we try out...?<br>A practical situation where this could be implemented is..." },
    { "front": "<img src='images/thinking/tm22.jpg'>", "back": "VARY: [change, alter]<br>Another way of thinking about it is...<br>What if we modify...?" },
    { "front": "<img src='images/thinking/tm23.jpg'>", "back": "WEIGH UP: [decide, judge]<br>Having listened closely, I conclude that...<br>Taking into account the pros and cons..." },
    { "front": "<img src='images/thinking/tm24.jpg'>", "back": "EXEMPLIFY: [give example, illustrate]<br>If we consider the case of...<br>I would like to give a real-life example..." },
    { "front": "<img src='images/thinking/tm25.jpg'>", "back": "YIELD: [accept, concede]<br>I have changed my thinking about...<br>Actually, that is a really good point..." },
    { "front": "<img src='images/thinking/tm26.jpg'>", "back": "ZOOM: [focus on, survey]<br>I would like to focus on...<br>Looking at this from a broader perspective..." }
]
