[
{ "front": "What is the capital of Bhutan?", "back": "Thimphu" },
{ "front": "Which country is known as the Land of the Midnight Sun?", "back": "Norway" },
{ "front": "What is the smallest country in South America?", "back": "Suriname" },
{ "front": "Which African country has three capital cities?", "back": "South Africa" },
{ "front": "What is the longest mountain range in the world?", "back": "The Andes" },
{ "front": "Which sea is the saltiest body of water on Earth?", "back": "The Dead Sea" },
{ "front": "What is the capital of Liechtenstein?", "back": "Vaduz" },
{ "front": "Which desert is the driest place on Earth?", "back": "The Atacama Desert" },
{ "front": "Which country owns Easter Island?", "back": "Chile" },
{ "front": "What is the capital of Mongolia?", "back": "Ulaanbaatar" },
{ "front": "Which European capital city is divided by the Danube River?", "back": "Budapest" },
{ "front": "Which country has the most time zones?", "back": "France (including territories)" },
{ "front": "Which country is completely surrounded by South Africa?", "back": "Lesotho" },
{ "front": "What is the largest landlocked country in the world?", "back": "Kazakhstan" },
{ "front": "Which ocean surrounds the Maldives?", "back": "The Indian Ocean" },
{ "front": "What is the southernmost city in the world?", "back": "Puerto Williams, Chile" },
{ "front": "Which island nation lies closest to the Equator?", "back": "Kiribati" },
{ "front": "Which river is known as the 'Yellow River'?", "back": "The Huang He (China)" },
{ "front": "What is the deepest oceanic trench in the world?", "back": "The Mariana Trench" },
{ "front": "Which African country was never colonized?", "back": "Ethiopia" },
{ "front": "What is the capital of Iceland?", "back": "Reykjavik" },
{ "front": "Which European country has the most volcanoes?", "back": "Italy" },
{ "front": "Which strait separates Europe and Asia?", "back": "The Bosphorus Strait" },
{ "front": "What is the capital of Paraguay?", "back": "Asunción" },
{ "front": "Which U.S. state is home to the Grand Canyon?", "back": "Arizona" },
{ "front": "Which island nation has Suva as its capital?", "back": "Fiji" },
{ "front": "What is the official language of Brazil?", "back": "Portuguese" },
{ "front": "What is the capital of Madagascar?", "back": "Antananarivo" },
{ "front": "Which mountain range separates Europe and Asia?", "back": "The Ural Mountains" },
{ "front": "What is the capital of Slovakia?", "back": "Bratislava" },
{ "front": "Which country is known for its pampas?", "back": "Argentina" },
{ "front": "What is the capital of Azerbaijan?", "back": "Baku" },
{ "front": "Which lake is known as the 'Pearl of Siberia'?", "back": "Lake Baikal" },
{ "front": "What is the northernmost capital city in the world?", "back": "Reykjavik, Iceland" },
{ "front": "Which country is known as the 'Emerald Isle'?", "back": "Ireland" },
{ "front": "What is the name of the sea bordered by Jordan and Israel?", "back": "The Dead Sea" },
{ "front": "Which country does the city of Timbuktu belong to?", "back": "Mali" },
{ "front": "What is the capital of North Korea?", "back": "Pyongyang" },
{ "front": "Which desert covers much of Botswana?", "back": "The Kalahari Desert" },
{ "front": "Which river is the primary water source for Egypt?", "back": "The Nile" },
{ "front": "Which mountain range forms the backbone of Italy?", "back": "The Apennines" },
{ "front": "Which country has the most UNESCO World Heritage Sites?", "back": "Italy" },
{ "front": "What is the capital of Papua New Guinea?", "back": "Port Moresby" },
{ "front": "What is the name of the region known as the roof of the world?", "back": "The Pamir Mountains" },
{ "front": "Which country is home to Angkor Wat?", "back": "Cambodia" },
{ "front": "Which river is the lifeline of Pakistan?", "back": "The Indus River" },
{ "front": "Which European country borders both the Mediterranean and the Atlantic?", "back": "Spain" },
{ "front": "What is the capital of Sri Lanka?", "back": "Sri Jayawardenepura Kotte" },
{ "front": "Which country is known for the ancient city of Machu Picchu?", "back": "Peru" },
{ "front": "What is the capital of Andorra?", "back": "Andorra la Vella" },
{ "front": "Which country has the largest number of islands?", "back": "Sweden" },
{ "front": "What is the capital of Brunei?", "back": "Bandar Seri Begawan" },
{ "front": "Which is the only country to have a square flag?", "back": "Switzerland" },
{ "front": "What is the smallest ocean in the world?", "back": "The Arctic Ocean" },
{ "front": "Which U.S. state is closest to Russia?", "back": "Alaska" },
{ "front": "Which country is known for its Maple Leaf flag?", "back": "Canada" },
{ "front": "What is the capital of Uzbekistan?", "back": "Tashkent" },
{ "front": "Which is the second-largest French-speaking city in the world?", "back": "Kinshasa, Democratic Republic of Congo" },
{ "front": "What is the capital of Croatia?", "back": "Zagreb" },
{ "front": "Which African country is shaped like a horizontal 'S'?", "back": "Senegal" },
{ "front": "What is the capital of Qatar?", "back": "Doha" },
{ "front": "Which country has the highest number of pyramids?", "back": "Sudan" },
{ "front": "What is the capital of Cyprus?", "back": "Nicosia" },
{ "front": "Which is the largest desert in Asia?", "back": "The Gobi Desert" },
{ "front": "Which country lies directly south of Saudi Arabia?", "back": "Yemen" },
{ "front": "What is the name of the sea separating Australia and New Zealand?", "back": "The Tasman Sea" },
{ "front": "What is the capital of Bahrain?", "back": "Manama" },
{ "front": "Which European country has Vaduz as its capital?", "back": "Liechtenstein" },
{ "front": "What is the name of the largest bay in the world?", "back": "The Bay of Bengal" },
{ "front": "What is the capital of Djibouti?", "back": "Djibouti" },
{ "front": "Which country is known for the ancient ruins of Petra?", "back": "Jordan" },
{ "front": "Which is the smallest country in Central America?", "back": "El Salvador" },
{ "front": "What is the capital of Armenia?", "back": "Yerevan" },
{ "front": "Which river forms the border between the U.S. and Mexico?", "back": "The Rio Grande" },
{ "front": "What is the capital of Kosovo?", "back": "Pristina" },
{ "front": "What is the name of the peninsula shared by Spain and Portugal?", "back": "The Iberian Peninsula" },
{ "front": "Which is the longest river in Europe?", "back": "The Volga River" },
{ "front": "What is the capital of Georgia (the country)?", "back": "Tbilisi" },
{ "front": "Which ocean is Bermuda located in?", "back": "The Atlantic Ocean" },
{ "front": "What is the capital of Laos?", "back": "Vientiane" },
{ "front": "What is the name of the largest coral reef system in the world?", "back": "The Great Barrier Reef" },
{ "front": "What is the capital of Maldives?", "back": "Malé" },
{ "front": "Which country has the city of Salzburg?", "back": "Austria" },
{ "front": "Which river flows through Paris?", "back": "The Seine" },
{ "front": "Which country owns the Galápagos Islands?", "back": "Ecuador" },
{ "front": "What is the capital of Turkmenistan?", "back": "Ashgabat" },
{ "front": "What is the highest peak in North America?", "back": "Denali (Mount McKinley)" },
{ "front": "Which African country is bordered by both the Atlantic and Indian Oceans?", "back": "South Africa" },
{ "front": "What is the capital of Vietnam?", "back": "Hanoi" },
{ "front": "Which is the largest freshwater lake by volume?", "back": "Lake Baikal" },
{ "front": "What is the capital of Cambodia?", "back": "Phnom Penh" },
{ "front": "Which desert covers most of Mongolia?", "back": "The Gobi Desert" },
{ "front": "Which country does the Canary Islands belong to?", "back": "Spain" },
{ "front": "What is the capital of Lithuania?", "back": "Vilnius" },
{ "front": "What is the capital of Myanmar (Burma)?", "back": "Naypyidaw" },
{ "front": "Which two continents does the Suez Canal separate?", "back": "Africa and Asia" },
{ "front": "What is the capital of Slovenia?", "back": "Ljubljana" },
{ "front": "What is the largest active volcano in the world?", "back": "Mauna Loa (Hawaii)" },
{ "front": "Which country is known for the city of Dubrovnik?", "back": "Croatia" }

]